"""End-to-end test for the Scout agent.

Creates a project with a logframe, runs Scout on 2 synthetic test images,
verifies the extracted Evidence objects have valid bounding boxes within
image dimensions, and confirms evidence is persisted to ProjectMemory.

Requires ANTHROPIC_API_KEY to be set (this calls the real Opus 4.7 API).

Run: cd backend && uv run python agents/test_scout.py
"""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

from PIL import Image

# Allow running from the backend directory
backend_dir = str(Path(__file__).resolve().parent.parent)
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

from agents.scout import ScoutAgent
from memory.project_memory import ProjectMemory

# ─────────────────────────────────────────────────────────────
# Test data
# ─────────────────────────────────────────────────────────────

PROJECT_ID = "scout-test-project"
PROJECT_NAME = "Scout Agent Test Project"
DONOR = "World Bank"

LOGFRAME = """## Output 1: Farmer Producer Companies Established

| Indicator | Target | Unit |
|-----------|--------|------|
| 1.1 FPCs registered | 15 | FPCs |
| 1.2 Farmers enrolled | 10,000 | farmers |
| 1.3 Women farmer participation | 30% | percentage |

## Output 2: Infrastructure Development

| Indicator | Target | Unit |
|-----------|--------|------|
| 2.1 Cold storage facilities | 5 | facilities |
| 2.2 Sale points operational | 20 | sale points |

## Output 3: Capacity Building

| Indicator | Target | Unit |
|-----------|--------|------|
| 3.1 PHM trainings conducted | 50 | trainings |
| 3.2 Women's PHM trainings | 20 | trainings |
| 3.3 Stakeholders trained | 1,000 | people |
"""

# Synthetic test images generated by data/synthetic/generate_test_images.py
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
TEST_IMAGE_ENGLISH = REPO_ROOT / "data" / "synthetic" / "form_english.png"
TEST_IMAGE_HINDI = REPO_ROOT / "data" / "synthetic" / "form_hindi.png"


def validate_bounding_boxes(
    evidence_list: list,
    image_path: Path,
    image_label: str,
) -> None:
    """Verify all bounding boxes are within image dimensions.

    Args:
        evidence_list: List of Evidence objects to validate.
        image_path: Path to the source image (for reading dimensions).
        image_label: Human-readable label for error messages.
    """
    with Image.open(image_path) as img:
        width, height = img.size

    print(f"\n   Image dimensions: {width}x{height}")

    for ev in evidence_list:
        if not ev.bounding_boxes:
            print(f"   WARNING: {ev.evidence_id} has no bounding boxes")
            continue

        for i, box in enumerate(ev.bounding_boxes):
            x1 = box.get("x1", 0)
            y1 = box.get("y1", 0)
            x2 = box.get("x2", 0)
            y2 = box.get("y2", 0)

            assert x1 >= 0, (
                f"{image_label} {ev.evidence_id} box[{i}]: x1={x1} is negative"
            )
            assert y1 >= 0, (
                f"{image_label} {ev.evidence_id} box[{i}]: y1={y1} is negative"
            )
            assert x2 <= width, (
                f"{image_label} {ev.evidence_id} box[{i}]: x2={x2} exceeds width={width}"
            )
            assert y2 <= height, (
                f"{image_label} {ev.evidence_id} box[{i}]: y2={y2} exceeds height={height}"
            )
            assert x1 < x2, (
                f"{image_label} {ev.evidence_id} box[{i}]: x1={x1} >= x2={x2} (zero-width box)"
            )
            assert y1 < y2, (
                f"{image_label} {ev.evidence_id} box[{i}]: y1={y1} >= y2={y2} (zero-height box)"
            )
            print(f"   {ev.evidence_id} box[{i}]: ({x1},{y1})→({x2},{y2}) OK")


def run_test() -> None:
    """Run the full Scout agent end-to-end test."""

    # Verify test images exist
    assert TEST_IMAGE_ENGLISH.exists(), (
        f"Test image not found: {TEST_IMAGE_ENGLISH}. "
        f"Run: cd backend && uv run python ../data/synthetic/generate_test_images.py"
    )
    assert TEST_IMAGE_HINDI.exists(), (
        f"Test image not found: {TEST_IMAGE_HINDI}. "
        f"Run: cd backend && uv run python ../data/synthetic/generate_test_images.py"
    )

    # Use a temp directory for ProjectMemory
    tmp_dir = Path(tempfile.mkdtemp(prefix="poneglyph_scout_test_"))
    print(f"Test data directory: {tmp_dir}\n")

    try:
        memory = ProjectMemory(data_dir=tmp_dir)

        # ─── 1. Create project and load logframe ────────────
        print("=" * 60)
        print("1. Setting up test project")
        print("=" * 60)

        memory.create_project(PROJECT_ID, PROJECT_NAME, DONOR)
        memory.load_logframe(PROJECT_ID, LOGFRAME)
        print(f"   Created project: {PROJECT_ID}")
        print(f"   Logframe loaded: {len(LOGFRAME)} chars")

        # ─── 2. Run Scout on English form ────────────────────
        print("\n" + "=" * 60)
        print("2. Scout: English beneficiary registration form")
        print("=" * 60)

        scout = ScoutAgent(memory=memory)

        print(f"   Processing: {TEST_IMAGE_ENGLISH.name}")
        english_evidence = scout.run(
            project_id=PROJECT_ID,
            image_source=str(TEST_IMAGE_ENGLISH),
            logframe=LOGFRAME,
        )

        print(f"\n   Extracted {len(english_evidence)} evidence items:")
        for ev in english_evidence:
            print(f"     [{ev.confidence}] {ev.evidence_id}: {ev.summary[:70]}...")
            if ev.raw_text:
                print(f"       raw: {ev.raw_text[:70]}...")

        # ─── 3. Validate English form bounding boxes ─────────
        print("\n   Validating bounding boxes (English form):")
        validate_bounding_boxes(english_evidence, TEST_IMAGE_ENGLISH, "English")

        # ─── 4. Run Scout on Hindi form ──────────────────────
        print("\n" + "=" * 60)
        print("3. Scout: Hindi/English PHM training attendance form")
        print("=" * 60)

        print(f"   Processing: {TEST_IMAGE_HINDI.name}")
        hindi_evidence = scout.run(
            project_id=PROJECT_ID,
            image_source=str(TEST_IMAGE_HINDI),
            logframe=LOGFRAME,
        )

        print(f"\n   Extracted {len(hindi_evidence)} evidence items:")
        for ev in hindi_evidence:
            print(f"     [{ev.confidence}] {ev.evidence_id}: {ev.summary[:70]}...")
            if ev.raw_text:
                print(f"       raw: {ev.raw_text[:70]}...")

        # ─── 5. Validate Hindi form bounding boxes ───────────
        print("\n   Validating bounding boxes (Hindi form):")
        validate_bounding_boxes(hindi_evidence, TEST_IMAGE_HINDI, "Hindi")

        # ─── 6. Verify persistence to ProjectMemory ──────────
        print("\n" + "=" * 60)
        print("4. Verifying ProjectMemory persistence")
        print("=" * 60)

        all_evidence = memory.read_all_evidence(PROJECT_ID)
        total_expected = len(english_evidence) + len(hindi_evidence)
        print(f"\n   Evidence in memory: {len(all_evidence)}")
        print(f"   Expected: {total_expected}")

        for ev in all_evidence:
            status = ev.verification_status.value if ev.verification_status else "none"
            print(f"     [{status:>8}] {ev.evidence_id}: {ev.summary[:60]}...")

        # ─── 7. Check timeline ───────────────────────────────
        timeline = memory.read_timeline(PROJECT_ID)
        evidence_events = [
            e for e in timeline if e.event_type.value == "evidence_added"
        ]
        print(f"\n   Timeline evidence events: {len(evidence_events)}")

        # ─── Assertions ─────────────────────────────────────
        print("\n" + "=" * 60)
        print("ASSERTIONS")
        print("=" * 60)

        assert len(english_evidence) >= 1, (
            f"Scout should extract at least 1 evidence from English form, got {len(english_evidence)}"
        )
        assert len(hindi_evidence) >= 1, (
            f"Scout should extract at least 1 evidence from Hindi form, got {len(hindi_evidence)}"
        )
        assert len(all_evidence) == total_expected, (
            f"Memory should have {total_expected} evidence items, got {len(all_evidence)}"
        )
        assert len(evidence_events) == total_expected, (
            f"Timeline should have {total_expected} evidence_added events, got {len(evidence_events)}"
        )

        # Every evidence item should have at least one bounding box
        for ev in all_evidence:
            assert ev.bounding_boxes and len(ev.bounding_boxes) > 0, (
                f"{ev.evidence_id} has no bounding boxes"
            )
            assert ev.confidence is not None, (
                f"{ev.evidence_id} has no confidence score"
            )

        # All evidence should be PENDING (Auditor hasn't run)
        for ev in all_evidence:
            assert ev.verification_status.value == "pending", (
                f"{ev.evidence_id} should be pending, got {ev.verification_status.value}"
            )

        print("\n   ALL ASSERTIONS PASSED")

    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        print(f"\n   Cleaned up: {tmp_dir}")


if __name__ == "__main__":
    run_test()
